### ISSUE TITLE
🐛 Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by kmccarp** [moderneinc/support-public#3]
```
TypeError: Cannot read properties of null (reading 'path')
    at In (https://public.moderne.io/_next/static/chunks/pages/results/%5BrecipeResultId%5D/details/%5Brepo%5D-b438b88abea6b27a.js:1:34291)
    at Eo (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:63196)
    at xi (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:120436)
    at bs (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:109372)
    at gs (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:109300)
    at vs (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:109163)
    at as (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:105943)
    at ls (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:104494)
    at S (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:138469)
    at MessagePort.T (https://public.moderne.io/_next/static/chunks/framework-4ed89e9640adfb9e.js:1:139003)
```

https://public.moderne.io/results/eBnoa/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+b3BlbnJld3JpdGUvcmV3cml0ZS1yZWNpcGUtbWFya2Rvd24tZ2VuZXJhdG9yfn5tYWluIiwib3JpZ2luIjoiZ2l0aHViLmNvbSIsInBhdGgiOiJvcGVucmV3cml0ZS9yZXdyaXRlLXJlY2lwZS1tYXJrZG93bi1nZW5lcmF0b3IiLCJicmFuY2giOiJtYWluIiwib3JnYW5pemF0aW9uIjoib3BlbnJld3JpdGUiLCJuYW1lIjoicmV3cml0ZS1yZWNpcGUtbWFya2Rvd24tZ2VuZXJhdG9yIiwiaW5nZXN0ZWQiOm51bGx9?recipename=Add%20date%20bounds%20to%20OWASP%20suppressions

**Comment by kmccarp** [comment]
this happened during a UI deployment.
