### ISSUE TITLE
🐛 Cannot read properties of undefined (reading 'tags')

### ISSUE THREAD

**Issue by cthigh** [moderneinc/support-public#43]
I clicked through
![image](https://user-images.githubusercontent.com/17861985/236854888-db0fefa1-b4c0-4fe6-a736-ae2fb3d73032.png)

from here:  https://docs.openrewrite.org/recipes/cloudsuitability/findejbstateless

And got this error:
```
TypeError: Cannot read properties of undefined (reading 'tags')
    at X (https://public.moderne.io/_next/static/chunks/pages/recipes/%5BrecipeId%5D-6d6b35208fabd78f.js:1:20108)
    at ab (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:9:60917)
    at i (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:9:119475)
    at oO (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:9:99114)
    at https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:9:98981
    at oF (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:9:98988)
    at ox (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:9:95740)
    at oS (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:9:94295)
    at x (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:33:1373)
    at MessagePort.T (https://public.moderne.io/_next/static/chunks/framework-ce84985cd166733a.js:33:1903)
```

https://public.moderne.io/recipes/org.openrewrite.cloudsuitability.FindEjbStateless

**Comment by natedanner** [comment]
Loaded missing recipe artifact. This page now loads.

**Comment by cthigh** [comment]
Thanks!
